# Generated by Django 5.1 on 2024-09-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tole_App', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('city', models.CharField(default='other', max_length=20)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='places/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
