# Generated by Django 5.1 on 2024-09-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tole_App', '0006_remove_place_id_place_place_id_place_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
